import { chromium, devices } from 'playwright';
const D='/private/tmp/claude-501/-Users-abelgessesse/25b64ad0-2074-47af-9793-f5fe3a0e0e49/scratchpad/';
const pass=[],fail=[]; const ok=(c,m)=>(c?pass:fail).push(m);
const b=await chromium.launch();
async function journey(opts,label,shot){
  const p=await b.newPage(opts);
  const errs=[]; p.on('console',m=>m.type()==='error'&&errs.push(m.text())); p.on('pageerror',e=>errs.push('ERR '+e.message));
  let clicks=0; const t0=Date.now(); const el=()=>((Date.now()-t0)/1000).toFixed(0);
  await p.goto('https://mentable.co/login',{waitUntil:'networkidle'});
  ok(!(await p.textContent('body')).includes('Demo1234'), `${label}: no demo credentials on login`);
  await p.fill('input[type="email"]',process.argv[2]); await p.fill('input[type="password"]','QaFirstRun!2026');
  await p.locator('button[type="submit"]').click(); clicks++; await p.waitForTimeout(9000);
  ok(/profile\/setup/.test(p.url()), `${label}: routed to setup on first login`);
  ok(!(await p.textContent('body')).includes('Danger zone'), `${label}: no Delete account on the first-run screen`);
  for (let i=0;i<2;i++){ await p.locator('button:has-text("Continue")').click(); clicks++; await p.waitForTimeout(1400); }
  await p.locator('button:has-text("Investment Banking")').first().click(); clicks++; await p.waitForTimeout(300);
  await p.locator('button:has-text("Complete Profile")').click(); clicks++; await p.waitForTimeout(7000);
  const tSetup=el();
  const dash=await p.evaluate(()=>document.body.innerText);
  ok(!/Complete your profile/.test(dash), `${label}: dashboard no longer asks for a finished profile`);
  await p.goto('https://mentable.co/discover',{waitUntil:'networkidle'}); clicks++; await p.waitForTimeout(4500);
  const tDiscover=el();
  if(shot) await p.screenshot({path:D+'m-after-discover.png',fullPage:true});
  const disc=await p.evaluate(()=>document.body.innerText);
  ok(!/% match/.test(disc), `${label}: no empty percentage badge`);
  ok(!/\d\.\d \(\d+\)/.test(disc), `${label}: no unsupported star ratings on cards`);
  ok(['Christopher Floyd','Peter Keane','Travis Melvin'].every(n=>disc.includes(n)), `${label}: landing-page mentors present in Discover`);
  ok(!/Unknown|Name unavailable|Former member/.test(disc), `${label}: no broken identities`);
  ok(await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=1, `${label}: Discover no overflow`);
  await p.locator('a:has-text("View profile")').first().click(); clicks++; await p.waitForTimeout(4500);
  if(shot) await p.screenshot({path:D+'m-after-profile.png',fullPage:true});
  const prof=await p.evaluate(()=>document.body.innerText);
  ok(/No reviews yet/.test(prof), `${label}: profile says No reviews yet`);
  ok(!/Reviews\(\d+\)/.test(prof), `${label}: no fabricated review count`);
  ok(!/Why you match/.test(prof), `${label}: no empty match percentage on profile`);
  await p.getByRole('button',{name:/Request Mentorship/i}).first().click(); clicks++; await p.waitForTimeout(2200);
  const send=p.getByRole('button',{name:/Send Request/i});
  ok(await send.isDisabled(), `${label}: empty request cannot be sent`);
  ok(await p.locator('#request-why').count()===1, `${label}: request field has a programmatic label`);
  await p.locator('#request-why').fill('I saw your background in M&A and I want to understand what the analyst years actually look like before I commit to recruiting.');
  await p.waitForTimeout(600);
  ok(!(await send.isDisabled()), `${label}: a specific request can be sent`);
  await send.click(); clicks++; await p.waitForTimeout(6000);
  const tReq=el();
  if(shot) await p.screenshot({path:D+'m-after-sent.png',fullPage:true});
  const after=await p.evaluate(()=>document.body.innerText);
  ok(/Request Sent|pending/i.test(after), `${label}: submission confirmed in place`);
  ok(/Requests/.test(after), `${label}: tells the student where to track it`);
  const small=await p.evaluate(()=>{const o=[];document.querySelectorAll('a,button').forEach(e=>{const r=e.getBoundingClientRect();if(!r.width||!r.height)return;const c=getComputedStyle(e,'::after');if(Math.max(r.height,parseFloat(c.height)||0)<24||Math.max(r.width,parseFloat(c.width)||0)<24)o.push((e.textContent||'').trim().slice(0,24)+' '+Math.round(r.width)+'x'+Math.round(r.height));});return [...new Set(o)];});
  ok(small.length===0, `${label}: tap targets >= 24px: `+(small.join(' | ')||'all ok'));
  ok(await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=1, `${label}: no overflow after request`);
  const real=errs.filter(e=>!/favicon|404|Download the React/i.test(e));
  ok(real.length===0, `${label}: no console errors`+(real.length?' — '+real[0].slice(0,60):''));
  console.log(`${label}: setup done +${tSetup}s · discover +${tDiscover}s · request sent +${tReq}s · ${clicks} clicks`);
  await p.close();
}
await journey({...devices['iPhone 13']},'mobile',true);
console.log('PASS ('+pass.length+')'); pass.forEach(x=>console.log('  ✓ '+x));
if(fail.length){console.log('FAIL ('+fail.length+')'); fail.forEach(x=>console.log('  ✗ '+x));}
await b.close();
