import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:900}});
const UU=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
const found=[];
p.on('request',r=>{const u=r.url(); if(!/google-analytics|googletagmanager\.com\/g\/collect/.test(u))return;
  const sp=new URL(u).searchParams;
  for(const [k,v] of sp) if(UU.test(v)) found.push({param:k, value:v, event:sp.get('en')});
  const body=r.postData(); if(body&&UU.test(body)) found.push({param:'(POST body)', value:body.slice(0,160), event:sp.get('en')});
});
await p.goto('https://mentable.co/login',{waitUntil:'networkidle'});
await p.fill('input[type="email"]',process.argv[2]); await p.fill('input[type="password"]','QaPilot!2026');
await p.locator('button[type="submit"]').click(); await p.waitForTimeout(8000);
await p.goto('https://mentable.co/mentor/c1054ef9-7fb0-483d-b716-6676a6ead6b3',{waitUntil:'networkidle'}); await p.waitForTimeout(4000);
await p.goto('https://mentable.co/discover',{waitUntil:'networkidle'}); await p.waitForTimeout(4000);
console.log('params carrying a UUID:', found.length);
found.forEach(f=>console.log(`   event=${f.event} param=${f.param} value=${f.value.slice(0,110)}`));
await b.close();
