import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'node:fs';
const env=Object.fromEntries(readFileSync('.env.local','utf8').split('\n').filter(l=>l.includes('=')&&!l.trim().startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^["']|["']$/g,'')];}));
const a=createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_SERVICE_KEY,{auth:{persistSession:false}});
const {data:profs}=await a.from('profiles').select('id,first_name,last_name,role,is_demo,email,created_at').order('created_at');
const real=['Floyd','Keane','Melvin','Sheffer','Nations','Smith'];
console.log('── are the 6 invited mentors in the DB? ──');
for(const r of real){const hit=profs.find(p=>(p.last_name||'').includes(r)); console.log('  ',r.padEnd(10), hit?`FOUND ${hit.first_name} ${hit.last_name} <${hit.email}>`:'not in database');}
console.log('\n── email domains across all profiles ──');
const d={}; profs.forEach(p=>{const dom=(p.email||'').split('@')[1]||'(none)'; d[dom]=(d[dom]||0)+1;});
Object.entries(d).sort((x,y)=>y[1]-x[1]).forEach(([k,v])=>console.log('  ',k.padEnd(28),v));
console.log('\n── non-demo-domain accounts (candidate real users) ──');
profs.filter(p=>!/demo\.mentee\.app|getmentee\.com/.test(p.email||'')).forEach(p=>console.log('  ',p.role.padEnd(7),p.first_name,p.last_name,'<'+p.email+'>'));
console.log('\n── mentee fixtures visible anywhere? ──');
const {count:reqs}=await a.from('mentorship_requests').select('id',{count:'exact',head:true});
const {count:ms}=await a.from('mentorships').select('id',{count:'exact',head:true});
const {count:msg}=await a.from('messages').select('id',{count:'exact',head:true});
const {count:ses}=await a.from('sessions').select('id',{count:'exact',head:true});
console.log(`  requests=${reqs} mentorships=${ms} messages=${msg} sessions=${ses} (all between fixtures)`);
const {data:mp}=await a.from('mentor_profiles').select('*').limit(1);
console.log('\n── mentor_profiles columns ──'); console.log('  '+Object.keys(mp[0]).join(', '));
const {data:all}=await a.from('mentor_profiles').select('id,is_verified,is_available,is_founding_mentor,profile_complete');
const tally=(k)=>{const t={};all.forEach(r=>{t[String(r[k])]=(t[String(r[k])]||0)+1;});return JSON.stringify(t);};
for(const k of ['is_verified','is_available','is_founding_mentor','profile_complete']) console.log('  '+k.padEnd(20), tally(k));
