import { chromium } from 'playwright';
const D='/private/tmp/claude-501/-Users-abelgessesse/25b64ad0-2074-47af-9793-f5fe3a0e0e49/scratchpad/';
const EMAIL=process.argv[2], PW='QaFirstRun!2026';
const b = await chromium.launch();
const p = await b.newPage({viewport:{width:1440,height:900}});
let clicks=0, screens=0, required=0; const t0=Date.now();
const snap = async(tag)=>{ screens++;
  console.log(`\n── ${tag} (+${((Date.now()-t0)/1000).toFixed(0)}s, ${clicks} clicks) ${p.url().replace('https://mentable.co','')}`);
  const f=await p.evaluate(()=>[...document.querySelectorAll('input,select,textarea')].map(i=>({l:(i.labels?.[0]?.textContent?.trim()||i.name||i.placeholder||i.type),r:i.required,t:i.type})));
  const req=f.filter(x=>x.r); required=Math.max(required,0);
  if(f.length) console.log('   fields('+f.length+', '+req.length+' required): '+f.map(x=>x.l+(x.r?'*':'')).join(' · '));
  const step=await p.evaluate(()=>{const e=[...document.querySelectorAll('*')].find(x=>x.children.length===0&&/^(Basic Info|Background|Interests)$/.test(x.textContent.trim())); return e?document.body.innerText.match(/Basic Info|Background|Interests/g)?.join('/'):null;});
  if(step) console.log('   wizard steps visible: '+step);
  await p.screenshot({path:`${D}w-${screens}.png`, fullPage:true});
  return f;
};
await p.goto('https://mentable.co/login',{waitUntil:'networkidle'});
await p.fill('input[type="email"]',EMAIL); await p.fill('input[type="password"]',PW);
await p.locator('button[type="submit"]').click(); clicks++;
await p.waitForTimeout(9000);
await snap('WIZARD 1');
// step 1 -> 2
await p.locator('button:has-text("Continue")').click(); clicks++; await p.waitForTimeout(1800);
await snap('WIZARD 2');
const btns2 = await p.evaluate(()=>[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(Boolean));
console.log('   buttons: '+[...new Set(btns2)].slice(0,14).join(' · '));
await p.locator('button:has-text("Continue")').click().catch(async()=>{await p.locator('button:has-text("Next")').click();}); clicks++;
await p.waitForTimeout(1800);
await snap('WIZARD 3');
const btns3 = await p.evaluate(()=>[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(Boolean));
console.log('   buttons: '+[...new Set(btns3)].slice(0,18).join(' · '));
await b.close();
